### ISSUE TITLE
Blank authorized page in UniFi 4.7.5

### ISSUE THREAD

**Issue by soamz** [kaptk2/portal#5]
Hi, I just installed it and it works till the splash page. 
Even the data is getting loaded to the database table. 

But the authorized.php page is blank . 

See the screenshot here, 
http://prntscr.com/8s7fga

What could be the issue ?

**Comment by kaptk2** [comment]
What do your http logs say, anything?

**Comment by soamz** [comment]
Im making new fields and putting it to MAMP again now.
Do you suggest to try it directly on UniFi or on basic web browser and test until it works ?

**Comment by soamz** [comment]
Is there a way, we can make this authorized.php page to enter voucher page ?
SO, that when someone fills the form, then he should get a text message with the voucher page. 
And on authorized.php page, he should enter this voucher code and then get the access ?

**Comment by kaptk2** [comment]
Yes, that is possible. I have some code written that does exactly that for
a client.

**Comment by soamz** [comment]
Can I have the source code ?
Im struggling since last 3 weeks and hunting at UBNT forums without any hint. 

MY email is bothblogs@gmail.com

**Comment by kaptk2** [comment]
It isn't open code, I wrote it for a client and they own it. So I can't
just send it to you.  It only took a few hours to code up. The basic flow
is client fills out form, an SMS message is sent with code to login, login
page is presented to user where they enter the code and gain access for a
set amount of time (4 hours in this case).

**Comment by soamz** [comment]
EXACTLY!
Please send an email with the quote, if you could do the same for my SMS and Payment API and Im ready to pay for the code and time. 
Please let me know, as Im stuck in the middle of the desert without any help!

**Comment by kaptk2** [comment]
Sending an email to your gmail account shortly.

**Comment by soamz** [comment]
Amazing! Im waiting!

**Comment by soamz** [comment]
Email replied.
